# Generated by Django 5.2.16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contato",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("telefone", models.CharField(max_length=32)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("urgente", "Urgente"),
                            ("relacionamentos", "Relacionamentos"),
                            ("vida_espiritual", "Vida Espiritual"),
                            ("duvidas_biblicas", "Dúvidas Bíblicas"),
                            ("crescimento", "Crescimento Pessoal"),
                            ("familia", "Família"),
                            ("profissional", "Profissional"),
                            ("geral", "Geral"),
                        ],
                        default="geral",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("novo", "Novo"),
                            ("mensagem_enviada", "Mensagem enviada"),
                            ("aguardando_resposta", "Aguardando resposta"),
                            ("respondeu", "Respondeu"),
                            ("encerrado", "Encerrado"),
                        ],
                        default="novo",
                        max_length=32,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Média"),
                            ("baixa", "Baixa"),
                        ],
                        default="media",
                        max_length=16,
                    ),
                ),
                (
                    "whatsapp_verification",
                    models.CharField(
                        choices=[
                            ("verificado", "Verificado"),
                            ("invalido", "Inválido"),
                            ("nao_verificado", "Não verificado"),
                            ("verificando", "Verificando"),
                        ],
                        default="nao_verificado",
                        max_length=16,
                    ),
                ),
                ("ultima_verificacao_em", models.DateTimeField(blank=True, null=True)),
                ("ultima_mensagem", models.TextField(blank=True, null=True)),
                ("ultima_mensagem_em", models.DateTimeField(blank=True, null=True)),
                ("nao_lidas", models.PositiveIntegerField(default=0)),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("bairro", models.CharField(blank=True, max_length=255, null=True)),
                ("aniversario", models.DateField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contatos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-atualizado_em"],
            },
        ),
    ]
