import type { Contato, HistoricoContato } from "./types";

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split("T")[0];
}

function mondayOfWeeksAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n * 7);
  d.setDate(d.getDate() - d.getDay() + 1);
  return d.toISOString().split("T")[0];
}

export const mockContatos: Contato[] = [
  {
    id: 1,
    nome: "Mariana Costa",
    telefone: "+55 11 98221-4471",
    faixa_etaria: "26-35",
    classificacao: "Líder",
    envolvimento: "Alto",
    participacao: "Ministério de Louvor",
    aniversario: "1994-03-12",
    rede_social: "@marianacosta",
    bairro: "Jardim América",
    prioridade: "Média",
    ultima_mensagem: daysAgo(1),
    status: "Ativo",
    observacoes: "Confirmou presença no ensaio de quinta.",
  },
  {
    id: 2,
    nome: "Rafael Souza",
    telefone: "+55 11 97744-1029",
    faixa_etaria: "18-25",
    classificacao: "Novo Convertido",
    envolvimento: "Médio",
    participacao: "Célula Jovens",
    aniversario: "2001-07-22",
    rede_social: "@rafa.souza",
    bairro: "Vila Nova",
    prioridade: "Alta",
    ultima_mensagem: daysAgo(18),
    status: "Sumiu",
    observacoes: "Não responde há duas semanas. Última vez disse que estava desanimado.",
  },
  {
    id: 3,
    nome: "Beatriz Lima",
    telefone: "+55 11 96633-8850",
    faixa_etaria: "36-45",
    classificacao: "Membro",
    envolvimento: "Alto",
    participacao: "Intercessão",
    aniversario: "1988-11-02",
    rede_social: "@bia.lima",
    bairro: "Centro",
    prioridade: "Baixa",
    ultima_mensagem: daysAgo(2),
    status: "Ativo",
    observacoes: "Pediu oração pela mãe que está hospitalizada.",
  },
  {
    id: 4,
    nome: "João Pedro Alves",
    telefone: "+55 11 95522-3391",
    faixa_etaria: "46-60",
    classificacao: "Congregado",
    envolvimento: "Baixo",
    participacao: "Ainda não participa",
    aniversario: "1975-05-30",
    bairro: "Boa Vista",
    prioridade: "Alta",
    ultima_mensagem: daysAgo(26),
    status: "Inativo",
    observacoes: "Mudou de bairro recentemente, verificar se ainda tem interesse.",
  },
  {
    id: 5,
    nome: "Camila Ferreira",
    telefone: "+55 11 94411-7723",
    faixa_etaria: "26-35",
    classificacao: "Visitante",
    envolvimento: "Baixo",
    participacao: "Ainda não participa",
    aniversario: "1997-01-19",
    rede_social: "@camilaferreira",
    bairro: "Cidade Alta",
    prioridade: "Alta",
    ultima_mensagem: daysAgo(4),
    status: "Pendente",
    observacoes: "Visitou pela primeira vez há 2 domingos, aguardando retorno do convite pra célula.",
  },
  {
    id: 6,
    nome: "Lucas Martins",
    telefone: "+55 11 93300-6612",
    faixa_etaria: "18-25",
    classificacao: "Membro",
    envolvimento: "Alto",
    participacao: "Ministério Infantil",
    aniversario: "2000-09-08",
    rede_social: "@lucas.martins",
    bairro: "Jardim América",
    prioridade: "Baixa",
    ultima_mensagem: daysAgo(0),
    status: "Ativo",
    observacoes: "Ativo e engajado, sem pendências.",
  },
  {
    id: 7,
    nome: "Fernanda Rocha",
    telefone: "+55 11 92299-4456",
    faixa_etaria: "36-45",
    classificacao: "Líder",
    envolvimento: "Alto",
    participacao: "Célula Jovens",
    aniversario: "1990-12-14",
    rede_social: "@fe.rocha",
    bairro: "Vila Nova",
    prioridade: "Média",
    ultima_mensagem: daysAgo(6),
    status: "Ativo",
    observacoes: "Vai liderar o retiro de jovens em agosto.",
  },
  {
    id: 8,
    nome: "Gabriel Santos",
    telefone: "+55 11 91188-2245",
    faixa_etaria: "26-35",
    classificacao: "Novo Convertido",
    envolvimento: "Médio",
    participacao: "Escola Dominical",
    aniversario: "1996-04-27",
    bairro: "Centro",
    prioridade: "Alta",
    ultima_mensagem: daysAgo(15),
    status: "Pendente",
    observacoes: "Pediu para ser chamado pra próxima célula, ainda não confirmou.",
  },
  {
    id: 9,
    nome: "Larissa Pereira",
    telefone: "+55 11 90077-9931",
    faixa_etaria: "18-25",
    classificacao: "Membro",
    envolvimento: "Médio",
    participacao: "Ministério de Louvor",
    aniversario: "1999-06-05",
    rede_social: "@larissapereira",
    bairro: "Boa Vista",
    prioridade: "Baixa",
    ultima_mensagem: daysAgo(3),
    status: "Ativo",
    observacoes: "",
  },
  {
    id: 10,
    nome: "Thiago Oliveira",
    telefone: "+55 11 99988-1120",
    faixa_etaria: "46-60",
    classificacao: "Membro",
    envolvimento: "Baixo",
    participacao: "Intercessão",
    aniversario: "1978-08-17",
    bairro: "Cidade Alta",
    prioridade: "Média",
    ultima_mensagem: daysAgo(21),
    status: "Inativo",
    observacoes: "Viajou a trabalho, disse que volta a participar em agosto.",
  },
  {
    id: 11,
    nome: "Juliana Almeida",
    telefone: "+55 11 98844-3367",
    faixa_etaria: "26-35",
    classificacao: "Visitante",
    envolvimento: "Nenhum",
    participacao: "Ainda não participa",
    aniversario: "1993-02-24",
    rede_social: "@ju.almeida",
    bairro: "Jardim América",
    prioridade: "Alta",
    ultima_mensagem: daysAgo(9),
    status: "Pendente",
    observacoes: "Veio convidada pela Mariana, ainda não recebeu segundo contato.",
  },
  {
    id: 12,
    nome: "Pedro Henrique Dias",
    telefone: "+55 11 97733-5540",
    faixa_etaria: "18-25",
    classificacao: "Congregado",
    envolvimento: "Médio",
    participacao: "Célula Jovens",
    aniversario: "2002-10-11",
    bairro: "Vila Nova",
    prioridade: "Baixa",
    ultima_mensagem: daysAgo(5),
    status: "Ativo",
    observacoes: "",
  },
  {
    id: 13,
    nome: "Isabela Cardoso",
    telefone: "+55 11 96622-8814",
    faixa_etaria: "36-45",
    classificacao: "Líder",
    envolvimento: "Alto",
    participacao: "Ministério Infantil",
    aniversario: "1989-07-03",
    rede_social: "@isacardoso",
    bairro: "Centro",
    prioridade: "Média",
    ultima_mensagem: daysAgo(2),
    status: "Ativo",
    observacoes: "Organizando escala de voluntários do mês.",
  },
  {
    id: 14,
    nome: "Bruno Carvalho",
    telefone: "+55 11 95511-2298",
    faixa_etaria: "26-35",
    classificacao: "Membro",
    envolvimento: "Baixo",
    participacao: "Ainda não participa",
    aniversario: "1995-05-16",
    bairro: "Boa Vista",
    prioridade: "Alta",
    ultima_mensagem: daysAgo(33),
    status: "Sumiu",
    observacoes: "Sumiu após término de relacionamento, precisa de acompanhamento pastoral.",
  },
  {
    id: 15,
    nome: "Amanda Ribeiro",
    telefone: "+55 11 94400-7765",
    faixa_etaria: "18-25",
    classificacao: "Novo Convertido",
    envolvimento: "Alto",
    participacao: "Escola Dominical",
    aniversario: "2003-01-29",
    rede_social: "@amandaribeiro",
    bairro: "Cidade Alta",
    prioridade: "Baixa",
    ultima_mensagem: daysAgo(1),
    status: "Ativo",
    observacoes: "Muito animada, trouxe uma amiga no último culto.",
  },
  {
    id: 16,
    nome: "Diego Nascimento",
    telefone: "+55 11 93399-4471",
    faixa_etaria: "36-45",
    classificacao: "Congregado",
    envolvimento: "Baixo",
    participacao: "Ainda não participa",
    aniversario: "1987-09-21",
    bairro: "Jardim América",
    prioridade: "Média",
    ultima_mensagem: daysAgo(12),
    status: "Pendente",
    observacoes: "",
  },
  {
    id: 17,
    nome: "Patrícia Gomes",
    telefone: "+55 11 92288-6630",
    faixa_etaria: "46-60",
    classificacao: "Líder",
    envolvimento: "Alto",
    participacao: "Intercessão",
    aniversario: "1976-11-08",
    rede_social: "@pat.gomes",
    bairro: "Vila Nova",
    prioridade: "Baixa",
    ultima_mensagem: daysAgo(0),
    status: "Ativo",
    observacoes: "Referência para pedidos de oração da célula.",
  },
  {
    id: 18,
    nome: "Vitor Barbosa",
    telefone: "+55 11 91177-3325",
    faixa_etaria: "18-25",
    classificacao: "Membro",
    envolvimento: "Médio",
    participacao: "Ministério de Louvor",
    aniversario: "2000-03-03",
    bairro: "Centro",
    prioridade: "Baixa",
    ultima_mensagem: daysAgo(7),
    status: "Ativo",
    observacoes: "",
  },
  {
    id: 19,
    nome: "Carolina Teixeira",
    telefone: "+55 11 90066-8812",
    faixa_etaria: "26-35",
    classificacao: "Visitante",
    envolvimento: "Nenhum",
    participacao: "Ainda não participa",
    aniversario: "1998-06-30",
    rede_social: "@carolteixeira",
    bairro: "Boa Vista",
    prioridade: "Alta",
    ultima_mensagem: daysAgo(20),
    status: "Sumiu",
    observacoes: "Visitou uma vez há um mês, nunca mais respondeu.",
  },
  {
    id: 20,
    nome: "Eduardo Moreira",
    telefone: "+55 11 99977-2210",
    faixa_etaria: "36-45",
    classificacao: "Membro",
    envolvimento: "Médio",
    participacao: "Célula Jovens",
    aniversario: "1991-04-14",
    bairro: "Cidade Alta",
    prioridade: "Média",
    ultima_mensagem: daysAgo(8),
    status: "Ativo",
    observacoes: "",
  },
  {
    id: 21,
    nome: "Renata Correia",
    telefone: "+55 11 98855-1147",
    faixa_etaria: "18-25",
    classificacao: "Novo Convertido",
    envolvimento: "Baixo",
    participacao: "Escola Dominical",
    aniversario: "2001-12-05",
    rede_social: "@renatacorreia",
    bairro: "Jardim América",
    prioridade: "Alta",
    ultima_mensagem: daysAgo(16),
    status: "Pendente",
    observacoes: "Batizou há 1 mês, precisa entrar em uma célula.",
  },
  {
    id: 22,
    nome: "Marcos Vinícius",
    telefone: "+55 11 97722-3398",
    faixa_etaria: "46-60",
    classificacao: "Congregado",
    envolvimento: "Baixo",
    participacao: "Ainda não participa",
    aniversario: "1979-02-11",
    bairro: "Vila Nova",
    prioridade: "Baixa",
    ultima_mensagem: daysAgo(29),
    status: "Inativo",
    observacoes: "Frequenta só em datas comemorativas.",
  },
  {
    id: 23,
    nome: "Aline Monteiro",
    telefone: "+55 11 96611-4482",
    faixa_etaria: "26-35",
    classificacao: "Líder",
    envolvimento: "Alto",
    participacao: "Ministério Infantil",
    aniversario: "1994-08-23",
    rede_social: "@alinemonteiro",
    bairro: "Centro",
    prioridade: "Média",
    ultima_mensagem: daysAgo(1),
    status: "Ativo",
    observacoes: "Precisa de mais dois voluntários para o ministério infantil.",
  },
  {
    id: 24,
    nome: "Felipe Cunha",
    telefone: "+55 11 95500-6674",
    faixa_etaria: "18-25",
    classificacao: "Membro",
    envolvimento: "Médio",
    participacao: "Célula Jovens",
    aniversario: "1999-10-19",
    bairro: "Boa Vista",
    prioridade: "Alta",
    ultima_mensagem: daysAgo(14),
    status: "Pendente",
    observacoes: "Disse que estava doente, ver se já melhorou.",
  },
];

/**
 * historico_contatos derived from current contact state: one entry per
 * contact for each of the last 4 weeks, so the History page and the
 * assistant have trend data to reason over.
 */
export const mockHistorico: HistoricoContato[] = (() => {
  const rows: HistoricoContato[] = [];
  let id = 1;
  for (let week = 3; week >= 0; week--) {
    for (const c of mockContatos) {
      rows.push({
        id: id++,
        contato_id: c.id,
        semana_inicio: mondayOfWeeksAgo(week),
        ultima_mensagem: week === 0 ? c.ultima_mensagem : daysAgo(week * 7 + (c.id % 5)),
        status: c.status,
        prioridade: c.prioridade,
        observacoes: week === 0 ? c.observacoes : null,
      });
    }
  }
  return rows;
})();
