# Generated by Django 5.2.16 on 2026-07-14 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('categoria', models.CharField(choices=[('urgente', 'Urgente'), ('relacionamentos', 'Relacionamentos'), ('vida_espiritual', 'Vida Espiritual'), ('duvidas_biblicas', 'Duvidas Biblicas'), ('crescimento', 'Crescimento'), ('familia', 'Familia'), ('profissional', 'Profissional'), ('geral', 'Geral')], default='geral', max_length=32)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('mensagem_enviada', 'Mensagem Enviada'), ('aguardando_resposta', 'Aguardando Resposta'), ('respondeu', 'Respondeu'), ('encerrado', 'Encerrado')], default='novo', max_length=32)),
                ('prioridade', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baixa', 'Baixa')], default='media', max_length=16)),
                ('whatsapp_verification', models.CharField(choices=[('verificado', 'Verificado'), ('invalido', 'Invalido'), ('nao_verificado', 'Nao Verificado'), ('verificando', 'Verificando')], default='nao_verificado', max_length=16)),
                ('ultima_verificacao_em', models.DateTimeField(blank=True, null=True)),
                ('ultima_mensagem', models.TextField(blank=True, default='')),
                ('ultima_mensagem_em', models.DateTimeField(blank=True, null=True)),
                ('nao_lidas', models.PositiveIntegerField(default=0)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('bairro', models.CharField(blank=True, default='', max_length=255)),
                ('aniversario', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em'],
                'indexes': [models.Index(fields=['owner', 'telefone'], name='contact_owner_phone_idx')],
            },
        ),
    ]
