# Generated by Django 5.2.16 on 2026-07-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='avatar_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
