# Generated by Django 5.2.16 on 2026-07-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='grupos_comuns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='contact',
            name='wa_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
