# Generated by Django 5.2.16 on 2026-07-14 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uazapi_base_url', models.CharField(blank=True, default='', max_length=255)),
                ('uazapi_token_encrypted', models.CharField(blank=True, default='', max_length=500)),
                ('openai_api_key_encrypted', models.CharField(blank=True, default='', max_length=500)),
                ('whatsapp_connected_at', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
