# Generated by Django 5.2.16 on 2026-07-20 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='google_access_token_encrypted',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='userintegration',
            name='google_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userintegration',
            name='google_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userintegration',
            name='google_refresh_token_encrypted',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='userintegration',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
