# Generated by Django 5.2.16 on 2026-08-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_userintegration_google_access_token_encrypted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='shepherds_toolkit_connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userintegration',
            name='shepherds_toolkit_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userintegration',
            name='shepherds_toolkit_token_encrypted',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
