# Generated by Django 5.2.16 on 2026-07-14 17:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('in', 'In'), ('out', 'Out')], max_length=8)),
                ('content', models.TextField()),
                ('external_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contacts.contact')),
            ],
            options={
                'ordering': ['criado_em'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('contact', 'external_id'), name='unique_message_external_id_per_contact')],
            },
        ),
    ]
