# Generated by Django 5.2.16 on 2026-07-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='whatsapp_audio/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
