# Generated by Django 5.2.16 on 2026-07-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_message_file_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['enviado_em', 'criado_em']},
        ),
        migrations.AddField(
            model_name='message',
            name='enviado_em',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
