# Generated by Django 5.2.16 on 2026-07-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_alter_message_options_message_enviado_em'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': [models.OrderBy(models.F('enviado_em'), nulls_first=True), 'criado_em']},
        ),
    ]
