# Generated by Django 5.2.16 on 2026-08-10 12:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contactgroup'),
        ('whatsapp', '0005_alter_message_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='contacts.contact'),
        ),
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jid', models.CharField(max_length=64)),
                ('nome', models.CharField(blank=True, default='', max_length=255)),
                ('avatar_url', models.TextField(blank=True, default='')),
                ('participantes', models.PositiveIntegerField(default=0)),
                ('ultima_mensagem', models.TextField(blank=True, default='')),
                ('ultima_mensagem_em', models.DateTimeField(blank=True, null=True)),
                ('nao_lidas', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappgroup'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('group', 'external_id'), name='unique_message_external_id_per_group'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contact__isnull', False), ('group__isnull', True)), models.Q(('contact__isnull', True), ('group__isnull', False)), _connector='OR'), name='message_exactly_one_of_contact_or_group'),
        ),
        migrations.AddConstraint(
            model_name='whatsappgroup',
            constraint=models.UniqueConstraint(fields=('owner', 'jid'), name='unique_whatsapp_group_per_owner'),
        ),
    ]
