# Generated by Django 5.2.16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoContato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semana_inicio", models.DateField()),
                ("ultima_mensagem", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("novo", "Novo"),
                            ("mensagem_enviada", "Mensagem enviada"),
                            ("aguardando_resposta", "Aguardando resposta"),
                            ("respondeu", "Respondeu"),
                            ("encerrado", "Encerrado"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Média"),
                            ("baixa", "Baixa"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "contato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="contacts.contato",
                    ),
                ),
            ],
            options={
                "ordering": ["-semana_inicio"],
                "unique_together": {("contato", "semana_inicio")},
            },
        ),
    ]
